#ifndef EXCEPTION_NAMES
#define EXCEPTION_NAMES
extern const char* ERROR_INCORRECT_ROUTE_POINTS_NAME;
extern const char* ERROR_INCORRECT_ROUTE_POINTS_NAME_WHEN_COPYING;
extern const char* ERROR_INCORRECT_ROUTE_POINTS_NAME_WHEN_ASSIGN;


extern const char* ERROR_INCORRECT_ROUTE_START_NAME;
extern const char* ERROR_INCORRECT_ROUTE_START_NAME_WHEN_COPYING;
extern const char* ERROR_INCORRECT_ROUTE_START_NAME_WHEN_ASSIGN;


extern const char* ERROR_INCORRECT_ROUTE_FINISH_NAME;
extern const char* ERROR_INCORRECT_ROUTE_FINISH_NAME_WHEN_COPYING;
extern const char* ERROR_INCORRECT_ROUTE_FINISH_NAME_WHEN_ASSIGN;


extern const char* ERROR_INCORRECT_ROUTE_NUMBER;
extern const char* ERROR_INCORRECT_ROUTE_NUMBER_WHEN_COPYING;
extern const char* ERROR_INCORRECT_ROUTE_NUMBER_WHEN_ASSIGN;


extern const char* ERROR_WITH_FILE;
extern const char* ERROR_WITH_INPUT;


extern const char* ERROR_FILE_IS_NOT_OPEN;
extern const char* ERROR_INCORRECT_FILE_STRUCTURE;


extern const char* ERROR_INCORRECT_LINES_NUMBER;


extern const char* ERROR_INCORRECT_INDEX_OUT_OF_RANGE;
#endif

